apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-http-config
  namespace: myapp-prod
data:
  config: |
    # 이거 없으면 오류남
    events {}
    http {
      server {
        location / {
          root /data/html;
        }
        location /images {
          root /data;
        }
      }
    }
